const Images = [
  {name:'spacewalker',ratio:.95,title:'Desrption',format:'png'},
  {name:'fixie',ratio:1,title:'Desrption',format:'png'},
  {name:'bulk',ratio:.9,title:'Desrption',format:'jpg'},
  {name:'ui',ratio:.95,title:'Desrption',format:'png'},
  {name:'canap',ratio:.9,title:'Desrption',format:'png'},
  {name:'astronaut',ratio:1,title:'Desrption',format:'png'},
  {name:'gamer',ratio:.8,title:'Desrption',format:'png'},
  // {name:'designers',ratio:.9,title:'Desrption',format:'jpg'},
  // {name:'gardener',ratio:.7,title:'Desrption',format:'jpg'},
  {name:'harden',ratio:1,title:'Desrption',format:'png'},
  {name:'lebron',ratio:.8,title:'Desrption',format:'png'},
  {name:'miller',ratio: 1,title:'Desrption',format:'png'},
  {name:'porzingis',ratio:.8,title:'Desrption',format:'png'},
  {name:'westbrook',ratio:.9,title:'Desrption',format:'png'},
  {name:'michaelleague',ratio:1,title:'Desrption',format:'png'},
  {name:'moose',ratio:.7,title:'Desrption',format:'jpg'},
  {name:'poker',ratio:.9,title:'Desrption',format:'png'},
  {name:'police',ratio:.8,title:'Desrption',format:'jpg'},
  {name:'shoe',ratio:.7,title:'Desrption',format:'jpg'},
  {name:'villain',ratio:1,title:'Desrption',format:'png'},
  {name:'backpack',ratio:.8,title:'Desrption',format:'png'},
  {name:'jesus',ratio:1,title:'Desrption',format:'gif'},
  {name:'basket',ratio:.8,title:'Desrption',format:'gif'},
  {name:'drums',ratio:.9,title:'Desrption',format:'gif'},
  {name:'family',ratio:.7,title:'Desrption',format:'gif'},
]

export default Images
